# Generated by Django 2.2.16 on 2021-11-06 15:01

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='score_average',
            field=models.IntegerField(blank=True, default=0, validators=[reviews.validators.score_validation], verbose_name='Оценка'),
        ),
    ]
