# Generated by Django 2.2.16 on 2021-11-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211112_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='titles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.Title', verbose_name='произведения'),
        ),
    ]
