# Generated by Django 2.2.16 on 2021-11-10 14:05

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211110_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[reviews.validators.score_validation], verbose_name='Оценка'),
        ),
    ]
