# Generated by Django 2.2.16 on 2021-11-16 10:35

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211116_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[reviews.validators.score_validation], verbose_name='Оценка'),
        ),
    ]
