# Generated by Django 2.2.16 on 2021-11-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20211112_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'titles')},
        ),
    ]
