# Generated by Django 2.2.16 on 2021-11-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20211110_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
    ]
